### ISSUE TITLE
Breadcrumbs 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#1]
### User story

As a user, I would like to see where I am within the app and be able to return to previous levels. 

The project title should automatically populate within the breadcrumb trail. 

The Details tab does not need to be labeled and should be considered "home" 

### Acceptance criteria

- [ ] I can click on the levels of the breadcrumbs and navigate to that level 
- [ ] The current level is not clickable 
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example

When on the contents page: 
Dashboard > [Project Name] > Contents 

When on the details page: 
Dashboard > [Project Name] 

When on details edit page: 
Dashboard > [Project Name] > Edit 

When on approvals edit page: 
Dashboard > [Project Name] > Approval Settings > Edit 

### Implementation notes, if any
 - [ ] Would be nice to have a warning appear if navigating away from a page with unsaved edits. BG will create a ticket.

**Comment by beth-german** [comment]
@matthewjchandler does this seem good in concept? Will create mockup if so.

**Comment by matthewjchandler** [comment]
Yes, I think the conception is good. I'll look forward to some mockups, thanks @beth-german

**Comment by beth-german** [comment]
![image](https://github.com/user-attachments/assets/de054224-41da-4c04-ad92-3c9dfb531e76)

Here is the medium fidelity prototype. Need to know:
* Placement
* Size
* Hover behavior (what all links do? ) 
* Active state

**Comment by cass1ex** [comment]
**Breadcrumbs update:**

The updated breadcrumbs contain 4 states: active(current page), inactive(previous pages), hover and disabled. 
![Image](https://github.com/user-attachments/assets/c7a2bdf8-021a-43d5-96a3-c43e2934da99)
https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=13-3066&t=hQYCP2oJiWZyyU8x-4

![Image](https://github.com/user-attachments/assets/451fc8f5-61e4-4fb0-bf32-c71fe22821d1)
https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=10-425&t=hQYCP2oJiWZyyU8x-4

Breadcrumb has a 24px vertical gap to the top and 120px horizontal margin (the container margin) to the left. See screenshot for reference.

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/977
