### ISSUE TITLE
Dashboard Updates

### ISSUE THREAD

**Issue by Ka-YT** [pulibrary/aux#11]
Context:

- Move to tab layout: Active | Draft and Pending | Downloads | All activity 
- Recent activity persistent with tab for viewing all recent activity
- new project button above tabs
- "Welcome, [user]" 
- Fields for listings
- - Active: Title, my role, last updated, usage/capacity 
- - Draft pending: Title, my role, last updated, status  

Recent activities 
- Project level status changes
- Project level metadata changes (including roles) 

Downloads 
- Where downloads go
- Label for when:  These files expire. Please download again if you don't see your file. 

Design file: 
(https://docs.google.com/presentation/d/1D_Vq1f31dYB8Sku_121PoKD4HLhoNp-AbLqLxMDXfFs/edit?usp=sharing)

**Midlevel mockup** 
![image](https://github.com/user-attachments/assets/bed4c5b9-bd27-450d-b9bb-844c9398f766)

**Implementation details**
- Indicator for new projects on active project list; how long do they stay 'new' (until click on it) 
- Sort for title, role, storage, updated, status 

## Related Components 
- Dashboard Tabbed Navigation https://github.com/pulibrary/aux/issues/15
- Monitoring Panel https://github.com/pulibrary/aux/issues/16
- Active Projects Tab https://github.com/pulibrary/aux/issues/19
- Project Requests Tab https://github.com/pulibrary/aux/issues/20
- Downloads Tab https://github.com/pulibrary/aux/issues/21
- All Activity Tab https://github.com/pulibrary/aux/issues/22
- Recent Activity Box https://github.com/pulibrary/aux/issues/17
- Downloads Box https://github.com/pulibrary/aux/issues/18
- Tab notifications https://github.com/pulibrary/aux/issues/23
- Project Table notifications https://github.com/pulibrary/aux/issues/24

**Comment by beth-german** [comment]
Latest figma draft: 
![image](https://github.com/user-attachments/assets/cccdd636-2da0-4dd1-ab30-841a6e03e0b8)

**Comment by gnemade51** [comment]
**Updates to the dashboard:**

We are changing the above design to be more self-explanatory and easier to navigate. The dashboard will now include two levels of tabbed navigation - L1 and L2.

L1 : Projects
- L2: All
- L2: Active
- L2: Pending

L1: Activity
- L2: All
- L2: By Projects 

![image](https://github.com/user-attachments/assets/71b8dc7b-317c-4790-9dad-d27668afd388)

This is how we imagine the dashboard would look like:
![image](https://github.com/user-attachments/assets/d7ec6491-da67-4db1-adc7-10a478651e9d)

**Comment by beth-german** [comment]
Continued by: https://github.com/pulibrary/tigerdata-app/issues/995
