### ISSUE TITLE
Project Details Layout

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#12]
## Pending Project 

Users should be able to:
- Edit metadata (data manager, data sponsor) 
- Navigate to see file inventory page 
- Clear indicator of project status 
- Does not see mediaflux id 

System Admin user should be able to:
- Can not edit details metadata 
- Navigate to see file inventory page 
-  Navigate to create script page 
- Navigate to approval settings page 
- See mediaflux id 

**Midlevel Mockup**
![image](https://github.com/user-attachments/assets/7d9609c1-43c2-4b93-88d5-9a501e2f9f8e)

## Approved Project 

Users should be able to:
- Edit metadata (data manager, data sponsor) 
- Navigate to see file inventory page 
- Clear indicator of project status 

**Midlevel Mockup** 
![image](https://github.com/user-attachments/assets/796e4294-c99f-48bf-9cb1-170a9105e30b)

**Comment by beth-german** [comment]
Editable Fields by data manager and  data sponsor:
- Data manager
- Data users and permissions 
- Title
- Description 
- Affiliated groups 
- Project directory (only in pending state)

**Comment by cass1ex** [comment]
**Project Details Update**

Project Details as the second tab on the project page, with the consistent header, see reference #27 

Project Details contains 2 sections: **Project Roles and Project Description**, with same fields as the New Project Creation. Edit button at top right is a universal control for all metadata fields. 

**Default:**
- text only, no input box
- Data user table disabled (radio buttons and remove action being dark grey)
![image](https://github.com/user-attachments/assets/ed8acbf3-a6e8-43fd-a5c3-f188741bed32)

**Edit Mode:**
- "Edit" button switches to "Save Changes"
- Input boxes replace text field (same as Project Creation)
- Data user table enabled (radio buttons turned black & remove action turned red)
- Department(s) selection list appears
<img width="597" alt="Screenshot 2024-12-03 at 3 58 46 PM" src="https://github.com/user-attachments/assets/c7602101-424f-4200-82c1-62ba0c9792bd">

**Default with Request Under Review:**
- Fields that already requested for an update will have a "Request under review" badge next to the text field. Fields will remain locked until Admin approves or makes action.
<img width="592" alt="Screenshot 2024-12-03 at 4 01 28 PM" src="https://github.com/user-attachments/assets/da3d0705-60ba-49c4-abd5-c503ee5ce1e9">

**Edit Mode with Request Under Review:**
- Even in edit mode, the locked field cannot be changed until Admin approves or makes action.
<img width="591" alt="Screenshot 2024-12-03 at 4 02 11 PM" src="https://github.com/user-attachments/assets/8ee51a13-1581-4ddf-8a1b-c30f4088beb9">

Link to Figma mockups: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=1541-12941&t=g4NxcaGhpszNFgYl-4

**Comment by beth-german** [comment]
Continued by: https://github.com/pulibrary/tigerdata-app/issues/1084
