### ISSUE TITLE
File Inventory Display 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#13]
- Show preview of file inventory; show limited and add show more feature 
- Include summary information about the storage 
- Option to download a csv file of the project's file inventory 
- Custom Query will be a feature in the future and so consider how other action would be incorporated into this display 

## Current state 
![image](https://github.com/user-attachments/assets/13aff524-69e6-4e64-af07-7dc289cb3e5e)

## Midlevel Mockup 
![image](https://github.com/user-attachments/assets/8a86b4f1-3b5b-4874-91cf-37979483ec57)

## MHCI Mockup 

![image](https://github.com/user-attachments/assets/5daa7573-95b0-41ad-aa6e-523ba75a8f95)

## Questions for Matt
- Is the the amount of file shown a technical constraint? 
- Okay to change to "file inventory"?

**Comment by beth-german** [comment]
@matthewjchandler @kelynch 
Which of these fields are available to display for MVP?

![image](https://github.com/user-attachments/assets/908dacf2-1f1f-4f65-b017-2ad5a7a06420)

**Comment by matthewjchandler** [comment]
For MVP, I expect we can display storage usage and file count.

**Comment by gnemade51** [comment]
### Project Page - Content Preview

_**Context:** When users open a particular project from the dashboard they will land directly on this project page. The project page contains different tabs such as Content Preview, Details, View Create Script, and Approval Settings. Within these tabs, we are focussing on the Content Preview tab in this ticket._
![image](https://github.com/user-attachments/assets/3c90fa01-2ee7-4b15-acba-b9023a777e93)

**File Inventory**
The Content Preview will contain a card that provides information about the entire file inventory with a button to download the complete file list. This section will contain information like:

- Total Files (total number of files in the repository)
- Average File Size (to be calculated and displayed with the range of file sizes)
- Folder Levels (directory depth will be displayed)

The Download Complete List will open a modal (popup) as seen in ticket #<tbd>.

![image](https://github.com/user-attachments/assets/4117f175-b0e3-42c6-89f7-42a476e24c11)

**The Table**

_Info Section_
The table contains an info section at the top as seen in the above image. This section informs the user about the limits of the content that is being displayed within the table. This section is attached to the table as seen in the screenshot.

_Contents_
The table is supposed to display the first 100 files from the entire file inventory. However, when displaying these 100 files to the users, we will be splitting them into 5 pages. Hence, only the first 20 files will be displayed at once on each page within the table. 

The table will contain 4 columns - Name, Path, Size, and Last Updated.

The table will end with a fixed row of Pagination showing 5 pages with navigation arrows.

![Frame 437](https://github.com/user-attachments/assets/0e00ca25-accc-4eb5-92ee-16635627170d)

Figma Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=1407-11106&m=dev

**Comment by beth-german** [comment]
Continued by: https://github.com/pulibrary/tigerdata-app/issues/1066
