### ISSUE TITLE
Dashboard Tabbed Navigation

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#15]
Tabs include 
- Active projects 
- Project request
- Downloads 
- All Activity 

![image](https://github.com/user-attachments/assets/4a156c74-8df5-4769-90e0-f9ced663de5c)

## Related issues 
- Tab notifications #23

**Comment by cass1ex** [comment]
**Update**

Dashboard tab navigation follows the same tab template as Project Details Page

<img width="651" alt="Screenshot 2024-10-22 at 1 52 55 PM" src="https://github.com/user-attachments/assets/3b7e08da-4f7d-42e3-9df9-6689a7ae8db9">

**Active tab (orange underline) vs. Default tab**

<img width="954" alt="Screenshot 2024-10-22 at 1 53 51 PM" src="https://github.com/user-attachments/assets/3acc7bbe-a353-429a-8936-5ab20732717d">


Note that the grey line should be the same width as the main container/table, for example, when "Downloads" is the active tab, the line should expand to match the full table width.

<img width="875" alt="Screenshot 2024-10-22 at 1 58 58 PM" src="https://github.com/user-attachments/assets/65e628a4-c0f7-484c-baa2-cee5a4fb6b8c">

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/982
