### ISSUE TITLE
Monitoring Panel

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#16]
Right hand panel to monitor recent activity and downloads  

## Draft Figma
![image](https://github.com/user-attachments/assets/6efbdf69-c249-4b59-8b77-50755969644d)

## Related issues
- Recent Activity Box #17 
- Downloads Box #18

**Comment by cass1ex** [comment]
**Monitoring Panel Updates**

Monitoring panel on the right contains "recent activities" and "downloads".
<img width="205" alt="Screenshot 2024-11-12 at 4 06 13 PM" src="https://github.com/user-attachments/assets/b0966dbe-6b02-47b6-9fed-d04188778758">

See related issues #17 #18 for details.

Link to Figma mockup: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=992-14965&t=eWh2ThNq9a4qhOup-4

**Comment by beth-german** [comment]
Continued by: https://github.com/pulibrary/tigerdata-app/issues/1051
