### ISSUE TITLE
Recent Activity Box

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#17]
Box displays the recent activity on projects 
- View all takes you to the View all tab 
- Project title will take you to the specific project details page 

**Questions** 
- Can recent activity be grouped for a project?  
- What is the list of all possible recent activities that could be logged and what language 

## Draft Figma 

![image](https://github.com/user-attachments/assets/f423a8a1-b4ab-48e4-a5f0-65bc23b5002b)

**Comment by beth-german** [comment]
@kelynch, @matthewjchandler  and RDSS... We have a question about some of the functionality about recent activities. There is the idea of trying to group by project. How feasible is this? Is there a list of all the activities that get recorded and displayed to the user as an activity? 

Here are a few interactions on the idea for the recent activities box. Should we keep going with the idea of grouping or do we need to focus on one action per update?

![image](https://github.com/user-attachments/assets/d44344e3-0475-4199-908e-57e16618dfc8)

**Comment by matthewjchandler** [comment]
We don't have a comprehensive list of activities that will be recorded long-term, but there are two big things we've focused on so far: status changes (including an original project request) and file inventory downloads. I see in your mockups a third that I do also think would be good to track: role changes. You could track metadata revisions more generally as well, but I would highlight status changes and role changes as the most important for monitoring purposes. Download tracking is important for practical purposes.

As for the grouping direction, I strongly support it.

**Comment by gnemade51** [comment]
Updates to the Recent Activities Panel:

The recent activities panel will be a fixed window with a fixed height and width. The internal content will be scrollable. Recent activity will show updates from the past two days. 

Clicking on the 'View All' link will take the user to the 'Activity' tab on the dashboard.

The notifications will be clubbed together based on the project title.
![image](https://github.com/user-attachments/assets/3966aa33-1b0a-4b5d-abef-33f78a74e871)

Each row will contain a project title and at max two updates displayed upfront. If there are more updates for the same project, they will be hidden under a 'Show more' dropdown accordion.

Closed accordion:
![image](https://github.com/user-attachments/assets/75325792-87da-4f6f-9bf1-2a3657382b65)

Expanded accordion:
![image](https://github.com/user-attachments/assets/bdac6106-d04b-4b46-9cd8-746b1cc8c2aa)

Single update:
![image](https://github.com/user-attachments/assets/0b5f1fed-d782-43fd-af85-f79b640c52ea)

Note: the admin tag will have a separate color and the wording '(admin)' followed by their net ID to signify that the admin made the update.
![image](https://github.com/user-attachments/assets/6772c7fb-c2cb-41b4-8477-77bbc9d2fc4b)
![image](https://github.com/user-attachments/assets/3e4a5eee-d113-4965-9692-73bfc7bf2565)


with measurements:
![image](https://github.com/user-attachments/assets/281ef892-b012-4979-9da0-528951116209)

Figma Link:
Components link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=1001-5395&m=dev

Mockup Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=992-14965&m=dev

**Comment by beth-german** [comment]
Continued by: https://github.com/pulibrary/tigerdata-app/issues/1052
