### ISSUE TITLE
Downloads Box

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#18]
Box displays the recent downloads
- can click on download to download 
- view all takes you to all recent downloads 

## Draft figma 
![image](https://github.com/user-attachments/assets/32f68fcb-8063-476b-a137-f79fe46f36b6)

**Comment by beth-german** [comment]
![image](https://github.com/user-attachments/assets/98b3b488-59e7-4d13-819a-53bbac696b0b)

**Comment by gnemade51** [comment]
Updates to the Latest Downloads Panel:

The Latest Downloads panel is a fixed window with fixed height and width. The content within this window will be scrollable. The first 2.5 downloads will be visible on the panel in its default state - having 3rd card displayed half indicates to the user that the window is scrollable and has more content below.
![image](https://github.com/user-attachments/assets/e2c1246f-745d-4ddd-88d4-0cfa246cba60)

Each row will display the project title, days for expiry, and the size as shown in the above image.

We assume that at max there are as many download rows as the number of projects in this list.

Clicking on each row will take you to the respective project dashboard where users can download the file.

With Measurements:
![image](https://github.com/user-attachments/assets/752467fc-c3f2-47b9-8709-ff82d3e3388a)

Figma Link:
Components link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=1001-5395&m=dev

Mockup Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=992-14965&m=dev

**Comment by beth-german** [comment]
Continued by: https://github.com/pulibrary/tigerdata-app/issues/1053
