### ISSUE TITLE
Template: New project 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#2]
### User story

As a project sponsor, I would like to add a new project. 

### Acceptance criteria
- [ ] Predefined in Tickets related to https://github.com/pulibrary/tigerdata-app/issues/170  
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example

https://tigerdata-qa.princeton.edu/projects/new
 
![image](https://github.com/user-attachments/assets/844dd5d5-4402-4838-a353-895f2d73fce6)

### Implementation notes, if any
- Update new mockup for grid system 
- Alignment 
- Cancel and submit button design 
- Headings, h1, h2, h3, definitions 
- Indicators for required fields 
- What happens when a user submits without required fields 

### Related issues 
- Update interaction for adding single and multiple users

**Comment by cass1ex** [comment]
**Grid System Updates**
1220px main container, 120px margin on both sides, 20px gutter, 12 columns (82px each)

![Image](https://github.com/user-attachments/assets/09c935c8-89be-4249-817a-914cfb16c02f)

https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=11-538&t=hQYCP2oJiWZyyU8x-4

**Style Guide Updates**
Definitions of 6 heading levels (H1-H6), 8 body sizes, and color usage

![Image](https://github.com/user-attachments/assets/221fa52b-a007-487e-acf3-75e87ed8c00a)

https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=5-34&t=hQYCP2oJiWZyyU8x-4

**New mockup with updated grid and styles**
Noted that select single user (data manager) and multiple users (data users) are subject to change, referencing ticket #3 and #4; 
suggestion for adding a "Save" button in between cancel and submit buttons

![Image](https://github.com/user-attachments/assets/8d80085b-9bbb-4c9c-8970-c128e5a73c6c)

https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=10-425&t=hQYCP2oJiWZyyU8x-4

When submits without required fields: highlight text box in red with warning icon and message.

![Image](https://github.com/user-attachments/assets/dce0d0b4-6abb-4eb1-b5f6-22709fe2e871)

https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=29-556&t=hQYCP2oJiWZyyU8x-4

**Comment by beth-german** [comment]
Grid and style - Continued in: https://github.com/pulibrary/tigerdata-app/issues/978

New project layout - Continued in: https://github.com/pulibrary/tigerdata-app/issues/979

**Comment by beth-german** [comment]
Grid and style - Continued in: https://github.com/pulibrary/tigerdata-app/issues/978

New project layout - Continued in: https://github.com/pulibrary/tigerdata-app/issues/979
