### ISSUE TITLE
Project Requests Tab and Table 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#20]
Table of project request 
- Project title 
- My role 
- Project status (pending and (hopefully draft) 
- Last updated 

## Draft Figma

![image](https://github.com/user-attachments/assets/9183f892-4f34-4679-ad50-120d5cf50a46)

**Comment by cass1ex** [comment]
**Updates**

Table of Project Requests contains 4 columns (Project title, My role, Project status, and Last updated), with a "three-dot" icon indicating potential further actions, such as delete a draft or withdraw a pending project.

When hover, the row container turns to light grey.

![image](https://github.com/user-attachments/assets/720eaa46-333a-4f3d-b587-27714fffbe4a)

Link to Figma: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=458-4897&t=RDstEPZDVjAZhKuc-4

**Comment by beth-german** [comment]
Incorporated into projects table design. https://github.com/pulibrary/tigerdata-app/issues/1025
