### ISSUE TITLE
Downloads Tab

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#21]
- list or recent downloads and link to download file 
- Notice that files are deleted after 30 days

**Comment by gnemade51** [comment]
**Downloads Tab:**

The Downloads Tab on the Dashboard would look like below. The table width spans the entire page width leaving the margins on both sides. The table will display 10 entries at once, rest of the list will be moved to different pages within the table. The bottom of the table contains pagination for users to navigate to older download requests.
![image](https://github.com/user-attachments/assets/70c48944-9a0e-4fe5-90b4-4cb0b5a91acc)


The download status will have three stages - Processing; Expires in X days; Expired. 
- 'Processing' is displayed when user requests to download a file list and the system takes time to process the request. A download icon will show at the end of this row, but it will be disabled until the files are processed and are ready for download.
- 'Expires in X days' is displayed when the file list for the requested project is available. The number of days the file will be shown on this tag. A download icon will show at the end of this row.
- 'Expired' is displayed with the file is no longer downloadable and has been purged from the database. The download icon on the end of the row for this file will not show.
![image](https://github.com/user-attachments/assets/0ae39353-2000-4816-b77f-67bd427773a9)

Row:
Each row will have a hover state where the background color changes to light grey (#EEEEEE)
![image](https://github.com/user-attachments/assets/90d1c613-ac6e-4b2d-9e89-b4b34067bb17)

Pagination:
![image](https://github.com/user-attachments/assets/8313f493-20c0-42de-9d38-028dc611d474)


Figma Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=466-5369&m=dev

**Comment by beth-german** [comment]
Refined to be incorporated on the projects table.
