### ISSUE TITLE
Project Table notifications

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#24]
- In both the active project table and the project request table, an indicator should appear next to a project if there has been activity on the project since the last time the user logged. 
- Indicator should disappear after the user has viewed the project 
- If the user logged out and then logged in again without seeing the project, the indicator should remain. 
- If while User A is logged in and User B took action on a project, an indicator should appear for User A but not User B
- Users should not see indicators for actions they took on a project 
- An option to mark all as read should be available which would clear all indicators from the list 

## Related issues
- Tab notifications #23

**Comment by gnemade51** [comment]
**Project Table Notifications:**

The Project Table Notifications are 'NEW' tags that appear 4px right to the project name in a row. This tag will appear when there is a new activity in the table. The tag will disappear once, the user has viewed the item.

![image](https://github.com/user-attachments/assets/e4064f31-8c6d-44ed-ac90-e74ddf6dc9b1)

(Please ignore the structure of the table in this mockup for now)
Figma Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=418-3815&m=dev

**Comment by beth-german** [comment]
continued by: https://github.com/pulibrary/tigerdata-app/issues/1026
