### ISSUE TITLE
Adding Users - single no roles 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#3]
### User story

Add a user to data manager-
- Only allow users to select netid of users in the system 
- Interaction for when a netid is not in the system/available to add
- Way to remove or edit an entry 

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### Concrete example

https://tigerdata-qa.princeton.edu/projects/new

Current tiger data
![image](https://github.com/user-attachments/assets/f5d72faf-fe1e-464a-a793-547c3402b3ce)

Midlevel mockup 
![image](https://github.com/user-attachments/assets/268383be-a416-4cfc-b85a-e96453701dad)

**Comment by beth-german** [comment]
Data user ticket: https://github.com/pulibrary/tigerdata-app/issues/248

**Comment by gnemade51** [comment]
**Single Select Design Update:**

The single select dropdown contains 5 stages -> Closed, Expanded, Filled, Result Not Found, and Error - Not Filled.


Closed: When the page loads, the form field appears in this state
Expanded: When the user clicks on this box, the drawdown list expands. The dropdown list contains a text-based search filter that helps users search for NetID from the list.
Filled: Once the user selects the desired NetID the dropdown closes and the selected value appears on the label.

![image](https://github.com/user-attachments/assets/f43031d6-618b-4ccd-bbb5-dda0ad8d912c)

Result Not Found: When the NetID is not present in the dropdown list, the dropdown indicates that no results were found.
Error - Not Filled: When a user attempts to submit the request on the New Project Request page without filling in a required field, the system will display an error message next to the missed field.

![image](https://github.com/user-attachments/assets/a4f163b6-b5e1-4dcd-8679-3a3c5efec3da)

![image](https://github.com/user-attachments/assets/f8b463c9-f450-49ca-90ac-0770f58b9d1c)


Figma Link:
https://www.figma.com/proto/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?page-id=0%3A1&node-id=110-1260&node-type=frame&viewport=-6043%2C-149%2C0.5&t=1mf1N1Zp2iJznNPJ-1&scaling=scale-down&content-scaling=fixed

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/980
