### ISSUE TITLE
Header/Footer UI Design Update

### ISSUE THREAD

**Issue by Ka-YT** [pulibrary/aux#5]
Updated specs for the TD header & footer, see linked document for images, notes, comments:

[Design File](https://docs.google.com/document/d/1YILJiI2A6dumW9K6qUeUWX4zHY78KomJQGbUmeRLS_I/edit?usp=sharing)

### Header 

**Midlevel Mockup**
![image](https://github.com/user-attachments/assets/ae4166c1-1993-4dd1-86ce-eee72f04bc36)

**General Style**
- Black background #121212 (same as library website) 
- TigerData Logo, clickable to tigerdata home/dashboard
- Consideration should be given for accessibility 
- WCAG Guidelines 
- E.g. <h1 class="sr-only sr-site-name">Tiger Data</h1> 
- Utility navigation with optional links and account actions in top right
-- Potential options could include Contact Us, FAQ, ORCID@Princeton 

**Profile Drop Down** 
See: #6 
- This features is models off of ORCID@Princeton 
- Username will populate in the top right (either netid or pretty name) 
- Drop down to logout 
- A future feature could be a profile link or other user specific actions. 

### Footer 

**Midlevel mockup**
![image](https://github.com/user-attachments/assets/bad9fc9e-1c08-4fae-bcc9-6f1f75dee08b)

**General Style** 
Double Footer
Orange bard separating page content from footers 
Grey bar between footers 

**Top Footer - Application Footer** 
Logos from patterns: Princeton University Library, Office of the Dean of Research, PRDS, and Princeton Research Computing 
New logo appropriate for black background will need to be created for PRDS 
Version statement 

**Bottom Footer - Princeton Footer**
Link to Accessibility 
Trustees copyright statement 
Princeton logo with link to princeton.edu

**Comment by gnemade51** [comment]
Header and Footer Alignment and Resizing:

**Header:**
![image](https://github.com/user-attachments/assets/89aab2dc-0cef-480d-9db4-daa65614b9d1)

Measurements:
![image](https://github.com/user-attachments/assets/1c810e27-75f1-4b09-b971-f6bc9669ba2f)

**Footer:**
![image](https://github.com/user-attachments/assets/17bc1180-364a-4ffb-a07d-93056ed49cdd)

Measurements:
![image](https://github.com/user-attachments/assets/01ced8c7-6e7d-4a8c-8cc9-78afa45e0c0d)


Note: the 'Accessibility Help' link -> On Hover: Underline with 1px height and width covering text and icon with #FFF background color
![image](https://github.com/user-attachments/assets/6dc42283-64f6-40c5-a7ca-61ccb8750dfd)

![image](https://github.com/user-attachments/assets/18e07356-9a04-4b74-a15d-e5ed139a3022)


Figma Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=149-1623&m=dev

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/975
