### ISSUE TITLE
Login, Logout, User profile 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#6]
### User story

- After logged, user name should appear with option to logout (perhaps drop down) 
- User profile would eventually be in the same place (not for MVP) 

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Concrete example

**Current state** 
![image](https://github.com/user-attachments/assets/9c9a8c4e-2aa7-4a53-bef8-56fbd9085bd2)

**Midlevel Mockup** 
![image](https://github.com/user-attachments/assets/59575d4e-01fd-46f7-9f46-a3257bae53f3)

### Implementation notes, if any

**Related issues**
#5

**Comment by cass1ex** [comment]
**Update**

Header consists of TigerData logo (left), Contact Us, FAQ, and NetID (right), aligning in center. 
When click on the dropdown arrow next to user NetID, a menu appeared with [log out] option, in the future the menu should contain [Account Setting] or [User Profile] as well.

![Image](https://github.com/user-attachments/assets/e794fa30-6cd0-412f-b6d2-36d7ec7dcc32)


Detailed alignments in px (standard header width=1440px):

![Image](https://github.com/user-attachments/assets/8cd42b35-ae04-4f84-81a8-a71540521fef)
![Image](https://github.com/user-attachments/assets/055924a3-8bc1-4446-aa59-40003bbb39a2)

Figma Link: 
https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=149-1623&m=dev
