### ISSUE TITLE
Tabbed navigation 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#7]
### User story

Move from a button based navigation to horizontal tabs. 

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

### Concrete example

**Current state** 
![image](https://github.com/user-attachments/assets/d4a97fe1-5f51-4de0-b10f-6c9842e1b642)

**Midlevel Mockup: System admin with 4 tabs**
![image](https://github.com/user-attachments/assets/75a53fdf-7806-4198-a496-687ab71194d0)

**Midlevel Mockup: Data user with 2 tabs**

![image](https://github.com/user-attachments/assets/60cc8e0b-92bf-40ce-91ad-72213e4d05df)

### Implementation notes, if any
- Active state
- Hover state 
- "Return to dashboard" will be addressed by breadcrumbs #1

**Comment by beth-german** [comment]
@matthewjchandler Confirming that this is the direction this can go in?

**Comment by matthewjchandler** [comment]
Yes, I think the horizontal tab direction is great!

**Comment by cass1ex** [comment]
**Tab Update**

The updated horizontal tabs have 3 states: Active (orange underline), Default, and Hover (black underline), and might need to be paired with a horizontal grey line that expands across the main container (not a part of the tab component).

![Image](https://github.com/user-attachments/assets/7f617444-cb7c-4e28-bb5e-98f129853b6c)

Alignment details: 

![Image](https://github.com/user-attachments/assets/bc0882ea-c7e3-43cb-a673-ab1cb72ce8df)

Link to Figma:

https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=189-3338&m=dev

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/982
