### ISSUE TITLE
Do not display non-defined function 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/aux#8]
### User story

Hide for production 
* Withdraw project
* Deny project 
* Custom query 

Features in development or down the roadmap should not be displayed in production for release. 

### Acceptance criteria

- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
.

**Comment by beth-german** [comment]
@matthewjchandler Is this agreed upon? That for production, future features without ready functionality should not display for MVP release.

**Comment by beth-german** [comment]
@kelynch Is there a feature flipper for Tigerdata?

**Comment by matthewjchandler** [comment]
Yes, I agree that features without ready functionality should not display at all

**Comment by beth-german** [comment]
Continued in: https://github.com/pulibrary/tigerdata-app/issues/985
